# Generated by Django 6.0.2 on 2026-02-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_card_scanner_cost_userprofile_ticket_card_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='cost',
            field=models.FloatField(null=True),
        ),
    ]
